//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IfsSvnClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SvnCheckOut")]
        public string ProjectRoot {
            get {
                return ((string)(this["ProjectRoot"]));
            }
            set {
                this["ProjectRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("workspace")]
        public string ServerWorkSpace {
            get {
                return ((string)(this["ServerWorkSpace"]));
            }
            set {
                this["ServerWorkSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedProject {
            get {
                return ((string)(this["SelectedProject"]));
            }
            set {
                this["SelectedProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*Converge*")]
        public string Pattern {
            get {
                return ((string)(this["Pattern"]));
            }
            set {
                this["Pattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedProjectForBranchCreate {
            get {
                return ((string)(this["SelectedProjectForBranchCreate"]));
            }
            set {
                this["SelectedProjectForBranchCreate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("peumali.sudasinghe@ifsworld.com")]
        public string SupportPerson {
            get {
                return ((string)(this["SupportPerson"]));
            }
            set {
                this["SupportPerson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Houston, we have a problem!")]
        public string HeaderMessage {
            get {
                return ((string)(this["HeaderMessage"]));
            }
            set {
                this["HeaderMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nbproject")]
        public string ServerNbProject {
            get {
                return ((string)(this["ServerNbProject"]));
            }
            set {
                this["ServerNbProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberFiltering {
            get {
                return ((bool)(this["RememberFiltering"]));
            }
            set {
                this["RememberFiltering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectCheckedOutAtStartUp {
            get {
                return ((bool)(this["SelectCheckedOutAtStartUp"]));
            }
            set {
                this["SelectCheckedOutAtStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxProjectsFilter_text {
            get {
                return ((string)(this["TextBoxProjectsFilter_text"]));
            }
            set {
                this["TextBoxProjectsFilter_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxComponentFilter_text {
            get {
                return ((string)(this["TextBoxComponentFilter_text"]));
            }
            set {
                this["TextBoxComponentFilter_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("documentation")]
        public string ServerDocumentation {
            get {
                return ((string)(this["ServerDocumentation"]));
            }
            set {
                this["ServerDocumentation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Sri Lanka | https://cmbsvn01/svn/ifsapp</string>
  <string>Sweden | https://lkpsvn01/svn/ifsapp</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerUriList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerUriList"]));
            }
            set {
                this["ServerUriList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerUri {
            get {
                return ((string)(this["ServerUri"]));
            }
            set {
                this["ServerUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^/documentation/onlinedocframework/trunk")]
        public string ServerDocumentationOnlinedocframework {
            get {
                return ((string)(this["ServerDocumentationOnlinedocframework"]));
            }
            set {
                this["ServerDocumentationOnlinedocframework"] = value;
            }
        }
    }
}
